services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY:-localhost}/dms-backend:${VERSION:-latest}
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env.prod
    volumes:
      - file-storage:/app/files
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - dms-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY:-localhost}/dms-frontend:${VERSION:-latest}
    restart: always
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      - dms-network

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "15432:5432"
    env_file:
      - .env.prod
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-dms_db}
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - dms-network

volumes:
  db-data:
  file-storage:

networks:
  dms-network:
    driver: bridge
