services:
  backend:
    image: ${DOCKER_REGISTRY}/dms-backend:${VERSION}
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env.prod
    volumes:
      - file-storage:/app/files

  frontend:
    image: ${DOCKER_REGISTRY}/dms-frontend:${VERSION}
    restart: always
    depends_on:
      - backend

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env.prod
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  file-storage:
